/**
 * Generated by Scrooge
 * version: 18.4.0
 * rev: b64bcb47af2451b2e51a1ed1b3876f6c06c642b3
 * built at: 20180410-144039
 */
package ch.unibas.cs.gravis.realsense

import scala.collection.Map
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder


object ThriftTriangleCell extends ValidatingThriftStructCodec3[ThriftTriangleCell] {
    val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
    val Struct = new TStruct("ThriftTriangleCell")
    val Id1Field = new TField("id1", TType.I32, 1)
    val Id1FieldManifest = implicitly[Manifest[Int]]
    val Id2Field = new TField("id2", TType.I32, 2)
    val Id2FieldManifest = implicitly[Manifest[Int]]
    val Id3Field = new TField("id3", TType.I32, 3)
    val Id3FieldManifest = implicitly[Manifest[Int]]

    /**
     * Field information in declaration order.
     */
    lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
            Id1Field,
            false,
            true,
            Id1FieldManifest,
            _root_.scala.None,
            _root_.scala.None,
            immutable$Map.empty[String, String],
            immutable$Map.empty[String, String],
            None
        ),
        new ThriftStructFieldInfo(
            Id2Field,
            false,
            true,
            Id2FieldManifest,
            _root_.scala.None,
            _root_.scala.None,
            immutable$Map.empty[String, String],
            immutable$Map.empty[String, String],
            None
        ),
        new ThriftStructFieldInfo(
            Id3Field,
            false,
            true,
            Id3FieldManifest,
            _root_.scala.None,
            _root_.scala.None,
            immutable$Map.empty[String, String],
            immutable$Map.empty[String, String],
            None
        )
    )

    lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]

    /**
     * Checks that all required fields are non-null.
     */
    def validate(_item: ThriftTriangleCell): Unit = {
    }

    /**
     * Checks that the struct is a valid as a new instance. If there are any missing required or
     * construction required fields, return a non-empty list.
     */
    def validateNewInstance(item: ThriftTriangleCell): scala.Seq[com.twitter.scrooge.validation.Issue] = {
        val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

        buf ++= validateField(item.id1)
        buf ++= validateField(item.id2)
        buf ++= validateField(item.id3)
        buf.toList
    }

    def withoutPassthroughFields(original: ThriftTriangleCell): ThriftTriangleCell =
        new Immutable(
            id1 = {
                val field = original.id1
                field
            },
            id2 = {
                val field = original.id2
                field
            },
            id3 = {
                val field = original.id3
                field
            }
        )

    override def encode(_item: ThriftTriangleCell, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
    }


    private[this] def lazyDecode(_iprot: LazyTProtocol): ThriftTriangleCell = {

        var id1: Int = 0
        var _got_id1 = false
        var id2: Int = 0
        var _got_id2 = false
        var id3: Int = 0
        var _got_id3 = false

        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
        val _start_offset = _iprot.offset

        _iprot.readStructBegin()
        while (!_done) {
            val _field = _iprot.readFieldBegin()
            if (_field.`type` == TType.STOP) {
                _done = true
            } else {
                _field.id match {
                    case 1 =>
                        _field.`type` match {
                            case TType.I32 =>

                                id1 = readId1Value(_iprot)
                                _got_id1 = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'id1' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 2 =>
                        _field.`type` match {
                            case TType.I32 =>

                                id2 = readId2Value(_iprot)
                                _got_id2 = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'id2' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 3 =>
                        _field.`type` match {
                            case TType.I32 =>

                                id3 = readId3Value(_iprot)
                                _got_id3 = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'id3' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case _ =>
                        if (_passthroughFields == null)
                            _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                        _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
                }
                _iprot.readFieldEnd()
            }
        }
        _iprot.readStructEnd()

        if (!_got_id1) throw new TProtocolException("Required field 'id1' was not found in serialized data for struct ThriftTriangleCell")
        if (!_got_id2) throw new TProtocolException("Required field 'id2' was not found in serialized data for struct ThriftTriangleCell")
        if (!_got_id3) throw new TProtocolException("Required field 'id3' was not found in serialized data for struct ThriftTriangleCell")
        new LazyImmutable(
            _iprot,
            _iprot.buffer,
            _start_offset,
            _iprot.offset,
            id1,
            id2,
            id3,
            if (_passthroughFields == null)
                NoPassthroughFields
            else
                _passthroughFields.result()
        )
    }

    override def decode(_iprot: TProtocol): ThriftTriangleCell =
        _iprot match {
            case i: LazyTProtocol => lazyDecode(i)
            case i => eagerDecode(i)
        }

    private[realsense] def eagerDecode(_iprot: TProtocol): ThriftTriangleCell = {
        var id1: Int = 0
        var _got_id1 = false
        var id2: Int = 0
        var _got_id2 = false
        var id3: Int = 0
        var _got_id3 = false
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false

        _iprot.readStructBegin()
        while (!_done) {
            val _field = _iprot.readFieldBegin()
            if (_field.`type` == TType.STOP) {
                _done = true
            } else {
                _field.id match {
                    case 1 =>
                        _field.`type` match {
                            case TType.I32 =>
                                id1 = readId1Value(_iprot)
                                _got_id1 = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'id1' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 2 =>
                        _field.`type` match {
                            case TType.I32 =>
                                id2 = readId2Value(_iprot)
                                _got_id2 = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'id2' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 3 =>
                        _field.`type` match {
                            case TType.I32 =>
                                id3 = readId3Value(_iprot)
                                _got_id3 = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'id3' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case _ =>
                        if (_passthroughFields == null)
                            _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                        _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
                }
                _iprot.readFieldEnd()
            }
        }
        _iprot.readStructEnd()

        if (!_got_id1) throw new TProtocolException("Required field 'id1' was not found in serialized data for struct ThriftTriangleCell")
        if (!_got_id2) throw new TProtocolException("Required field 'id2' was not found in serialized data for struct ThriftTriangleCell")
        if (!_got_id3) throw new TProtocolException("Required field 'id3' was not found in serialized data for struct ThriftTriangleCell")
        new Immutable(
            id1,
            id2,
            id3,
            if (_passthroughFields == null)
                NoPassthroughFields
            else
                _passthroughFields.result()
        )
    }

    def apply(
                 id1: Int,
                 id2: Int,
                 id3: Int
             ): ThriftTriangleCell =
        new Immutable(
            id1,
            id2,
            id3
        )

    def unapply(_item: ThriftTriangleCell): _root_.scala.Option[_root_.scala.Tuple3[Int, Int, Int]] = _root_.scala.Some(_item.toTuple)


    @inline private[realsense] def readId1Value(_iprot: TProtocol): Int = {
        _iprot.readI32()
    }

    @inline private def writeId1Field(id1_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(Id1Field)
        writeId1Value(id1_item, _oprot)
        _oprot.writeFieldEnd()
    }

    @inline private def writeId1Value(id1_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeI32(id1_item)
    }

    @inline private[realsense] def readId2Value(_iprot: TProtocol): Int = {
        _iprot.readI32()
    }

    @inline private def writeId2Field(id2_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(Id2Field)
        writeId2Value(id2_item, _oprot)
        _oprot.writeFieldEnd()
    }

    @inline private def writeId2Value(id2_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeI32(id2_item)
    }

    @inline private[realsense] def readId3Value(_iprot: TProtocol): Int = {
        _iprot.readI32()
    }

    @inline private def writeId3Field(id3_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(Id3Field)
        writeId3Value(id3_item, _oprot)
        _oprot.writeFieldEnd()
    }

    @inline private def writeId3Value(id3_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeI32(id3_item)
    }


    object Immutable extends ThriftStructCodec3[ThriftTriangleCell] {
        override def encode(_item: ThriftTriangleCell, _oproto: TProtocol): Unit = {
            _item.write(_oproto)
        }

        override def decode(_iprot: TProtocol): ThriftTriangleCell = ThriftTriangleCell.decode(_iprot)

        override lazy val metaData: ThriftStructMetaData[ThriftTriangleCell] = ThriftTriangleCell.metaData
    }

    /**
     * The default read-only implementation of ThriftTriangleCell.  You typically should not need to
     * directly reference this class; instead, use the ThriftTriangleCell.apply method to construct
     * new instances.
     */
    class Immutable(
                       val id1: Int,
                       val id2: Int,
                       val id3: Int,
                       override val _passthroughFields: immutable$Map[Short, TFieldBlob])
        extends ThriftTriangleCell {
        def this(
                    id1: Int,
                    id2: Int,
                    id3: Int
                ) = this(
            id1,
            id2,
            id3,
            Map.empty[Short, TFieldBlob]
        )
    }

    /**
     * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
     * array byte on read.
     */
    private[this] class LazyImmutable(
                                         _proto: LazyTProtocol,
                                         _buf: Array[Byte],
                                         _start_offset: Int,
                                         _end_offset: Int,
                                         val id1: Int,
                                         val id2: Int,
                                         val id3: Int,
                                         override val _passthroughFields: immutable$Map[Short, TFieldBlob])
        extends ThriftTriangleCell {

        override def write(_oprot: TProtocol): Unit = {
            _oprot match {
                case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
                case _ => super.write(_oprot)
            }
        }


        /**
         * Override the super hash code to make it a lazy val rather than def.
         *
         * Calculating the hash code can be expensive, caching it where possible
         * can provide significant performance wins. (Key in a hash map for instance)
         * Usually not safe since the normal constructor will accept a mutable map or
         * set as an arg
         * Here however we control how the class is generated from serialized data.
         * With the class private and the contract that we throw away our mutable references
         * having the hash code lazy here is safe.
         */
        override lazy val hashCode = super.hashCode
    }

    /**
     * This Proxy trait allows you to extend the ThriftTriangleCell trait with additional state or
     * behavior and implement the read-only methods from ThriftTriangleCell using an underlying
     * instance.
     */
    trait Proxy extends ThriftTriangleCell {
        protected def _underlying_ThriftTriangleCell: ThriftTriangleCell

        override def id1: Int = _underlying_ThriftTriangleCell.id1

        override def id2: Int = _underlying_ThriftTriangleCell.id2

        override def id3: Int = _underlying_ThriftTriangleCell.id3

        override def _passthroughFields = _underlying_ThriftTriangleCell._passthroughFields
    }

}

/**
 * Prefer the companion object's [[ch.unibas.cs.gravis.realsense.ThriftTriangleCell.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait ThriftTriangleCell
    extends ThriftStruct
        with _root_.scala.Product3[Int, Int, Int]
        with ValidatingThriftStruct[ThriftTriangleCell]
        with java.io.Serializable {

    import ThriftTriangleCell._

    def id1: Int

    def id2: Int

    def id3: Int

    def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

    def _1 = id1

    def _2 = id2

    def _3 = id3

    def toTuple: _root_.scala.Tuple3[Int, Int, Int] = {
        (
            id1,
            id2,
            id3
        )
    }


    /**
     * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
     * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
     * is known and not optional and set to None, then the field is serialized and returned.
     */
    def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
        lazy val _buff = new TMemoryBuffer(32)
        lazy val _oprot = new TCompactProtocol(_buff)
        _passthroughFields.get(_fieldId) match {
            case blob: _root_.scala.Some[TFieldBlob] => blob
            case _root_.scala.None => {
                val _fieldOpt: _root_.scala.Option[TField] =
                    _fieldId match {
                        case 1 =>
                            if (true) {
                                writeId1Value(id1, _oprot)
                                _root_.scala.Some(ThriftTriangleCell.Id1Field)
                            } else {
                                _root_.scala.None
                            }
                        case 2 =>
                            if (true) {
                                writeId2Value(id2, _oprot)
                                _root_.scala.Some(ThriftTriangleCell.Id2Field)
                            } else {
                                _root_.scala.None
                            }
                        case 3 =>
                            if (true) {
                                writeId3Value(id3, _oprot)
                                _root_.scala.Some(ThriftTriangleCell.Id3Field)
                            } else {
                                _root_.scala.None
                            }
                        case _ => _root_.scala.None
                    }
                _fieldOpt match {
                    case _root_.scala.Some(_field) =>
                        _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
                    case _root_.scala.None =>
                        _root_.scala.None
                }
            }
        }
    }

    /**
     * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
     */
    def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
        (ids flatMap { id => getFieldBlob(id) map {
            id -> _
        }
        }).toMap

    /**
     * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
     * field, the blob is decoded and the field is set to the decoded value.  If the field
     * is unknown and passthrough fields are enabled, then the blob will be stored in
     * _passthroughFields.
     */
    def setField(_blob: TFieldBlob): ThriftTriangleCell = {
        var id1: Int = this.id1
        var id2: Int = this.id2
        var id3: Int = this.id3
        var _passthroughFields = this._passthroughFields
        _blob.id match {
            case 1 =>
                id1 = readId1Value(_blob.read)
            case 2 =>
                id2 = readId2Value(_blob.read)
            case 3 =>
                id3 = readId3Value(_blob.read)
            case _ => _passthroughFields += (_blob.id -> _blob)
        }
        new Immutable(
            id1,
            id2,
            id3,
            _passthroughFields
        )
    }

    /**
     * If the specified field is optional, it is set to None.  Otherwise, if the field is
     * known, it is reverted to its default value; if the field is unknown, it is removed
     * from the passthroughFields map, if present.
     */
    def unsetField(_fieldId: Short): ThriftTriangleCell = {
        var id1: Int = this.id1
        var id2: Int = this.id2
        var id3: Int = this.id3

        _fieldId match {
            case 1 =>
                id1 = 0
            case 2 =>
                id2 = 0
            case 3 =>
                id3 = 0
            case _ =>
        }
        new Immutable(
            id1,
            id2,
            id3,
            _passthroughFields - _fieldId
        )
    }

    /**
     * If the specified field is optional, it is set to None.  Otherwise, if the field is
     * known, it is reverted to its default value; if the field is unknown, it is removed
     * from the passthroughFields map, if present.
     */
    def unsetId1: ThriftTriangleCell = unsetField(1)

    def unsetId2: ThriftTriangleCell = unsetField(2)

    def unsetId3: ThriftTriangleCell = unsetField(3)


    override def write(_oprot: TProtocol): Unit = {
        ThriftTriangleCell.validate(this)
        _oprot.writeStructBegin(Struct)
        writeId1Field(id1, _oprot)
        writeId2Field(id2, _oprot)
        writeId3Field(id3, _oprot)
        if (_passthroughFields.nonEmpty) {
            _passthroughFields.values.foreach {
                _.write(_oprot)
            }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
    }

    def copy(
                id1: Int = this.id1,
                id2: Int = this.id2,
                id3: Int = this.id3,
                _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
            ): ThriftTriangleCell =
        new Immutable(
            id1,
            id2,
            id3,
            _passthroughFields
        )

    override def canEqual(other: Any): Boolean = other.isInstanceOf[ThriftTriangleCell]

    private def _equals(x: ThriftTriangleCell, y: ThriftTriangleCell): Boolean =
        x.productArity == y.productArity &&
            x.productIterator.sameElements(y.productIterator)

    override def equals(other: Any): Boolean =
        canEqual(other) &&
            _equals(this, other.asInstanceOf[ThriftTriangleCell]) &&
            _passthroughFields == other.asInstanceOf[ThriftTriangleCell]._passthroughFields

    override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

    override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


    override def productArity: Int = 3

    override def productElement(n: Int): Any = n match {
        case 0 => this.id1
        case 1 => this.id2
        case 2 => this.id3
        case _ => throw new IndexOutOfBoundsException(n.toString)
    }

    override def productPrefix: String = "ThriftTriangleCell"

    def _codec: ValidatingThriftStructCodec3[ThriftTriangleCell] = ThriftTriangleCell
}

