/**
 * Generated by Scrooge
 * version: 18.4.0
 * rev: b64bcb47af2451b2e51a1ed1b3876f6c06c642b3
 * built at: 20180410-144039
 */
package ch.unibas.cs.gravis.realsense

import scala.collection.Map
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder


object ThriftServerError extends ValidatingThriftStructCodec3[ThriftServerError] {
    val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
    val Struct = new TStruct("ThriftServerError")
    val MessageField = new TField("message", TType.STRING, 1)
    val MessageFieldManifest = implicitly[Manifest[String]]
    val StackTraceField = new TField("stackTrace", TType.STRING, 2)
    val StackTraceFieldManifest = implicitly[Manifest[String]]

    /**
     * Field information in declaration order.
     */
    lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
            MessageField,
            false,
            false,
            MessageFieldManifest,
            _root_.scala.None,
            _root_.scala.None,
            immutable$Map.empty[String, String],
            immutable$Map.empty[String, String],
            None
        ),
        new ThriftStructFieldInfo(
            StackTraceField,
            false,
            false,
            StackTraceFieldManifest,
            _root_.scala.None,
            _root_.scala.None,
            immutable$Map.empty[String, String],
            immutable$Map.empty[String, String],
            None
        )
    )

    lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]

    /**
     * Checks that all required fields are non-null.
     */
    def validate(_item: ThriftServerError): Unit = {
    }

    /**
     * Checks that the struct is a valid as a new instance. If there are any missing required or
     * construction required fields, return a non-empty list.
     */
    def validateNewInstance(item: ThriftServerError): scala.Seq[com.twitter.scrooge.validation.Issue] = {
        val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

        buf ++= validateField(item.message)
        buf ++= validateField(item.stackTrace)
        buf.toList
    }

    def withoutPassthroughFields(original: ThriftServerError): ThriftServerError =
        new ThriftServerError(
            message = {
                val field = original.message
                field
            },
            stackTrace = {
                val field = original.stackTrace
                field
            }
        )

    override def encode(_item: ThriftServerError, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
    }


    override def decode(_iprot: TProtocol): ThriftServerError = {
        var message: String = null
        var stackTrace: String = null
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false

        _iprot.readStructBegin()
        while (!_done) {
            val _field = _iprot.readFieldBegin()
            if (_field.`type` == TType.STOP) {
                _done = true
            } else {
                _field.id match {
                    case 1 =>
                        _field.`type` match {
                            case TType.STRING =>
                                message = readMessageValue(_iprot)
                            case _actualType =>
                                val _expectedType = TType.STRING
                                throw new TProtocolException(
                                    "Received wrong type for field 'message' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 2 =>
                        _field.`type` match {
                            case TType.STRING =>
                                stackTrace = readStackTraceValue(_iprot)
                            case _actualType =>
                                val _expectedType = TType.STRING
                                throw new TProtocolException(
                                    "Received wrong type for field 'stackTrace' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case _ =>
                        if (_passthroughFields == null)
                            _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                        _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
                }
                _iprot.readFieldEnd()
            }
        }
        _iprot.readStructEnd()

        new ThriftServerError(
            message,
            stackTrace,
            if (_passthroughFields == null)
                NoPassthroughFields
            else
                _passthroughFields.result()
        )
    }

    def apply(
                 message: String,
                 stackTrace: String
             ): ThriftServerError =
        new ThriftServerError(
            message,
            stackTrace
        )

    def unapply(_item: ThriftServerError): _root_.scala.Option[_root_.scala.Tuple2[String, String]] = _root_.scala.Some(_item.toTuple)


    @inline private[realsense] def readMessageValue(_iprot: TProtocol): String = {
        _iprot.readString()
    }

    @inline private def writeMessageField(message_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(MessageField)
        writeMessageValue(message_item, _oprot)
        _oprot.writeFieldEnd()
    }

    @inline private def writeMessageValue(message_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeString(message_item)
    }

    @inline private[realsense] def readStackTraceValue(_iprot: TProtocol): String = {
        _iprot.readString()
    }

    @inline private def writeStackTraceField(stackTrace_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(StackTraceField)
        writeStackTraceValue(stackTrace_item, _oprot)
        _oprot.writeFieldEnd()
    }

    @inline private def writeStackTraceValue(stackTrace_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeString(stackTrace_item)
    }


}

/**
 * Prefer the companion object's [[ch.unibas.cs.gravis.realsense.ThriftServerError.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
class ThriftServerError(
                           val message: String,
                           val stackTrace: String,
                           val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends ThriftException with com.twitter.finagle.SourcedException with ThriftStruct
        with _root_.scala.Product2[String, String]
        with ValidatingThriftStruct[ThriftServerError]
        with java.io.Serializable {

    import ThriftServerError._

    def this(
                message: String,
                stackTrace: String
            ) = this(
        message,
        stackTrace,
        Map.empty
    )

    def _1 = message

    def _2 = stackTrace

    def toTuple: _root_.scala.Tuple2[String, String] = {
        (
            message,
            stackTrace
        )
    }


    /**
     * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
     * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
     * is known and not optional and set to None, then the field is serialized and returned.
     */
    def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
        lazy val _buff = new TMemoryBuffer(32)
        lazy val _oprot = new TCompactProtocol(_buff)
        _passthroughFields.get(_fieldId) match {
            case blob: _root_.scala.Some[TFieldBlob] => blob
            case _root_.scala.None => {
                val _fieldOpt: _root_.scala.Option[TField] =
                    _fieldId match {
                        case 1 =>
                            if (message ne null) {
                                writeMessageValue(message, _oprot)
                                _root_.scala.Some(ThriftServerError.MessageField)
                            } else {
                                _root_.scala.None
                            }
                        case 2 =>
                            if (stackTrace ne null) {
                                writeStackTraceValue(stackTrace, _oprot)
                                _root_.scala.Some(ThriftServerError.StackTraceField)
                            } else {
                                _root_.scala.None
                            }
                        case _ => _root_.scala.None
                    }
                _fieldOpt match {
                    case _root_.scala.Some(_field) =>
                        _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
                    case _root_.scala.None =>
                        _root_.scala.None
                }
            }
        }
    }

    /**
     * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
     */
    def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
        (ids flatMap { id => getFieldBlob(id) map {
            id -> _
        }
        }).toMap

    /**
     * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
     * field, the blob is decoded and the field is set to the decoded value.  If the field
     * is unknown and passthrough fields are enabled, then the blob will be stored in
     * _passthroughFields.
     */
    def setField(_blob: TFieldBlob): ThriftServerError = {
        var message: String = this.message
        var stackTrace: String = this.stackTrace
        var _passthroughFields = this._passthroughFields
        _blob.id match {
            case 1 =>
                message = readMessageValue(_blob.read)
            case 2 =>
                stackTrace = readStackTraceValue(_blob.read)
            case _ => _passthroughFields += (_blob.id -> _blob)
        }
        new ThriftServerError(
            message,
            stackTrace,
            _passthroughFields
        )
    }

    /**
     * If the specified field is optional, it is set to None.  Otherwise, if the field is
     * known, it is reverted to its default value; if the field is unknown, it is removed
     * from the passthroughFields map, if present.
     */
    def unsetField(_fieldId: Short): ThriftServerError = {
        var message: String = this.message
        var stackTrace: String = this.stackTrace

        _fieldId match {
            case 1 =>
                message = null
            case 2 =>
                stackTrace = null
            case _ =>
        }
        new ThriftServerError(
            message,
            stackTrace,
            _passthroughFields - _fieldId
        )
    }

    /**
     * If the specified field is optional, it is set to None.  Otherwise, if the field is
     * known, it is reverted to its default value; if the field is unknown, it is removed
     * from the passthroughFields map, if present.
     */
    def unsetMessage: ThriftServerError = unsetField(1)

    def unsetStackTrace: ThriftServerError = unsetField(2)


    override def write(_oprot: TProtocol): Unit = {
        ThriftServerError.validate(this)
        _oprot.writeStructBegin(Struct)
        if (message ne null) writeMessageField(message, _oprot)
        if (stackTrace ne null) writeStackTraceField(stackTrace, _oprot)
        if (_passthroughFields.nonEmpty) {
            _passthroughFields.values.foreach {
                _.write(_oprot)
            }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
    }

    def copy(
                message: String = this.message,
                stackTrace: String = this.stackTrace,
                _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
            ): ThriftServerError =
        new ThriftServerError(
            message,
            stackTrace,
            _passthroughFields
        )

    override def canEqual(other: Any): Boolean = other.isInstanceOf[ThriftServerError]

    private def _equals(x: ThriftServerError, y: ThriftServerError): Boolean =
        x.productArity == y.productArity &&
            x.productIterator.sameElements(y.productIterator)

    override def equals(other: Any): Boolean =
        canEqual(other) &&
            _equals(this, other.asInstanceOf[ThriftServerError]) &&
            _passthroughFields == other.asInstanceOf[ThriftServerError]._passthroughFields

    override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

    override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)

    override def getMessage: String = String.valueOf(message)

    override def productArity: Int = 2

    override def productElement(n: Int): Any = n match {
        case 0 => this.message
        case 1 => this.stackTrace
        case _ => throw new IndexOutOfBoundsException(n.toString)
    }

    override def productPrefix: String = "ThriftServerError"

    def _codec: ValidatingThriftStructCodec3[ThriftServerError] = ThriftServerError
}

