/**
 * Generated by Scrooge
 *   version: 18.4.0
 *   rev: b64bcb47af2451b2e51a1ed1b3876f6c06c642b3
 *   built at: 20180410-144039
 */
package ch.unibas.cs.gravis.realsense

import com.twitter.io.Buf
import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil,
  ValidatingThriftStruct,
  ValidatingThriftStructCodec3
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object ThriftLandmark2D extends ValidatingThriftStructCodec3[ThriftLandmark2D] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("ThriftLandmark2D")
  val NameField = new TField("name", TType.STRING, 1)
  val NameFieldManifest = implicitly[Manifest[String]]
  val PixelsField = new TField("pixels", TType.STRUCT, 2)
  val PixelsFieldManifest = implicitly[Manifest[ch.unibas.cs.gravis.realsense.ThriftPixel]]
  val UncertaintyField = new TField("uncertainty", TType.DOUBLE, 3)
  val UncertaintyFieldManifest = implicitly[Manifest[Double]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      NameField,
      false,
      true,
      NameFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      PixelsField,
      false,
      true,
      PixelsFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      UncertaintyField,
      true,
      false,
      UncertaintyFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: ThriftLandmark2D): Unit = {
    if (_item.name == null) throw new TProtocolException("Required field name cannot be null")
    if (_item.pixels == null) throw new TProtocolException("Required field pixels cannot be null")
  }

  /**
   * Checks that the struct is a valid as a new instance. If there are any missing required or
   * construction required fields, return a non-empty list.
   */
  def validateNewInstance(item: ThriftLandmark2D): scala.Seq[com.twitter.scrooge.validation.Issue] = {
    val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

    if (item.name == null)
      buf += com.twitter.scrooge.validation.MissingRequiredField(fieldInfos.apply(0))
    buf ++= validateField(item.name)
    if (item.pixels == null)
      buf += com.twitter.scrooge.validation.MissingRequiredField(fieldInfos.apply(1))
    buf ++= validateField(item.pixels)
    buf ++= validateField(item.uncertainty)
    buf.toList
  }

  def withoutPassthroughFields(original: ThriftLandmark2D): ThriftLandmark2D =
    new Immutable(
      name =
        {
          val field = original.name
          field
        },
      pixels =
        {
          val field = original.pixels
          ch.unibas.cs.gravis.realsense.ThriftPixel.withoutPassthroughFields(field)
        },
      uncertainty =
        {
          val field = original.uncertainty
          field.map { field =>
            field
          }
        }
    )

  override def encode(_item: ThriftLandmark2D, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): ThriftLandmark2D = {

    var nameOffset: Int = -1
    var _got_name = false
    var pixels: ch.unibas.cs.gravis.realsense.ThriftPixel = null
    var _got_pixels = false
    var uncertaintyOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                nameOffset = _iprot.offsetSkipString
    
                _got_name = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'name' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRUCT =>
    
                pixels = readPixelsValue(_iprot)
                _got_pixels = true
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'pixels' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.DOUBLE =>
                uncertaintyOffset = _iprot.offsetSkipDouble
    
              case _actualType =>
                val _expectedType = TType.DOUBLE
                throw new TProtocolException(
                  "Received wrong type for field 'uncertainty' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_name) throw new TProtocolException("Required field 'name' was not found in serialized data for struct ThriftLandmark2D")
    if (!_got_pixels) throw new TProtocolException("Required field 'pixels' was not found in serialized data for struct ThriftLandmark2D")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      nameOffset,
      pixels,
      uncertaintyOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): ThriftLandmark2D =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[realsense] def eagerDecode(_iprot: TProtocol): ThriftLandmark2D = {
    var name: String = null
    var _got_name = false
    var pixels: ch.unibas.cs.gravis.realsense.ThriftPixel = null
    var _got_pixels = false
    var uncertainty: _root_.scala.Option[Double] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                name = readNameValue(_iprot)
                _got_name = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'name' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRUCT =>
                pixels = readPixelsValue(_iprot)
                _got_pixels = true
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'pixels' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.DOUBLE =>
                uncertainty = _root_.scala.Some(readUncertaintyValue(_iprot))
              case _actualType =>
                val _expectedType = TType.DOUBLE
                throw new TProtocolException(
                  "Received wrong type for field 'uncertainty' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_name) throw new TProtocolException("Required field 'name' was not found in serialized data for struct ThriftLandmark2D")
    if (!_got_pixels) throw new TProtocolException("Required field 'pixels' was not found in serialized data for struct ThriftLandmark2D")
    new Immutable(
      name,
      pixels,
      uncertainty,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    name: String,
    pixels: ch.unibas.cs.gravis.realsense.ThriftPixel,
    uncertainty: _root_.scala.Option[Double] = _root_.scala.None
  ): ThriftLandmark2D =
    new Immutable(
      name,
      pixels,
      uncertainty
    )

  def unapply(_item: ThriftLandmark2D): _root_.scala.Option[_root_.scala.Tuple3[String, ch.unibas.cs.gravis.realsense.ThriftPixel, Option[Double]]] = _root_.scala.Some(_item.toTuple)


  @inline private[realsense] def readNameValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeNameField(name_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(NameField)
    writeNameValue(name_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeNameValue(name_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(name_item)
  }

  @inline private[realsense] def readPixelsValue(_iprot: TProtocol): ch.unibas.cs.gravis.realsense.ThriftPixel = {
    ch.unibas.cs.gravis.realsense.ThriftPixel.decode(_iprot)
  }

  @inline private def writePixelsField(pixels_item: ch.unibas.cs.gravis.realsense.ThriftPixel, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(PixelsField)
    writePixelsValue(pixels_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writePixelsValue(pixels_item: ch.unibas.cs.gravis.realsense.ThriftPixel, _oprot: TProtocol): Unit = {
    pixels_item.write(_oprot)
  }

  @inline private[realsense] def readUncertaintyValue(_iprot: TProtocol): Double = {
    _iprot.readDouble()
  }

  @inline private def writeUncertaintyField(uncertainty_item: Double, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(UncertaintyField)
    writeUncertaintyValue(uncertainty_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeUncertaintyValue(uncertainty_item: Double, _oprot: TProtocol): Unit = {
    _oprot.writeDouble(uncertainty_item)
  }


  object Immutable extends ThriftStructCodec3[ThriftLandmark2D] {
    override def encode(_item: ThriftLandmark2D, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): ThriftLandmark2D = ThriftLandmark2D.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[ThriftLandmark2D] = ThriftLandmark2D.metaData
  }

  /**
   * The default read-only implementation of ThriftLandmark2D.  You typically should not need to
   * directly reference this class; instead, use the ThriftLandmark2D.apply method to construct
   * new instances.
   */
  class Immutable(
      val name: String,
      val pixels: ch.unibas.cs.gravis.realsense.ThriftPixel,
      val uncertainty: _root_.scala.Option[Double],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends ThriftLandmark2D {
    def this(
      name: String,
      pixels: ch.unibas.cs.gravis.realsense.ThriftPixel,
      uncertainty: _root_.scala.Option[Double] = _root_.scala.None
    ) = this(
      name,
      pixels,
      uncertainty,
      Map.empty[Short, TFieldBlob]
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      nameOffset: Int,
      val pixels: ch.unibas.cs.gravis.realsense.ThriftPixel,
      uncertaintyOffset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends ThriftLandmark2D {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val name: String =
      if (nameOffset == -1)
        null
      else {
        _proto.decodeString(_buf, nameOffset)
      }
    lazy val uncertainty: _root_.scala.Option[Double] =
      if (uncertaintyOffset == -1)
        None
      else {
        Some(_proto.decodeDouble(_buf, uncertaintyOffset))
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the ThriftLandmark2D trait with additional state or
   * behavior and implement the read-only methods from ThriftLandmark2D using an underlying
   * instance.
   */
  trait Proxy extends ThriftLandmark2D {
    protected def _underlying_ThriftLandmark2D: ThriftLandmark2D
    override def name: String = _underlying_ThriftLandmark2D.name
    override def pixels: ch.unibas.cs.gravis.realsense.ThriftPixel = _underlying_ThriftLandmark2D.pixels
    override def uncertainty: _root_.scala.Option[Double] = _underlying_ThriftLandmark2D.uncertainty
    override def _passthroughFields = _underlying_ThriftLandmark2D._passthroughFields
  }
}

/**
 * Prefer the companion object's [[ch.unibas.cs.gravis.realsense.ThriftLandmark2D.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait ThriftLandmark2D
  extends ThriftStruct
  with _root_.scala.Product3[String, ch.unibas.cs.gravis.realsense.ThriftPixel, Option[Double]]
  with ValidatingThriftStruct[ThriftLandmark2D]
  with java.io.Serializable
{
  import ThriftLandmark2D._

  def name: String
  def pixels: ch.unibas.cs.gravis.realsense.ThriftPixel
  def uncertainty: _root_.scala.Option[Double]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = name
  def _2 = pixels
  def _3 = uncertainty

  def toTuple: _root_.scala.Tuple3[String, ch.unibas.cs.gravis.realsense.ThriftPixel, Option[Double]] = {
    (
      name,
      pixels,
      uncertainty
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (name ne null) {
                writeNameValue(name, _oprot)
                _root_.scala.Some(ThriftLandmark2D.NameField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (pixels ne null) {
                writePixelsValue(pixels, _oprot)
                _root_.scala.Some(ThriftLandmark2D.PixelsField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (uncertainty.isDefined) {
                writeUncertaintyValue(uncertainty.get, _oprot)
                _root_.scala.Some(ThriftLandmark2D.UncertaintyField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): ThriftLandmark2D = {
    var name: String = this.name
    var pixels: ch.unibas.cs.gravis.realsense.ThriftPixel = this.pixels
    var uncertainty: _root_.scala.Option[Double] = this.uncertainty
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        name = readNameValue(_blob.read)
      case 2 =>
        pixels = readPixelsValue(_blob.read)
      case 3 =>
        uncertainty = _root_.scala.Some(readUncertaintyValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      name,
      pixels,
      uncertainty,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): ThriftLandmark2D = {
    var name: String = this.name
    var pixels: ch.unibas.cs.gravis.realsense.ThriftPixel = this.pixels
    var uncertainty: _root_.scala.Option[Double] = this.uncertainty

    _fieldId match {
      case 1 =>
        name = null
      case 2 =>
        pixels = null
      case 3 =>
        uncertainty = _root_.scala.None
      case _ =>
    }
    new Immutable(
      name,
      pixels,
      uncertainty,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetName: ThriftLandmark2D = unsetField(1)

  def unsetPixels: ThriftLandmark2D = unsetField(2)

  def unsetUncertainty: ThriftLandmark2D = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    ThriftLandmark2D.validate(this)
    _oprot.writeStructBegin(Struct)
    if (name ne null) writeNameField(name, _oprot)
    if (pixels ne null) writePixelsField(pixels, _oprot)
    if (uncertainty.isDefined) writeUncertaintyField(uncertainty.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    name: String = this.name,
    pixels: ch.unibas.cs.gravis.realsense.ThriftPixel = this.pixels,
    uncertainty: _root_.scala.Option[Double] = this.uncertainty,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): ThriftLandmark2D =
    new Immutable(
      name,
      pixels,
      uncertainty,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[ThriftLandmark2D]

  private def _equals(x: ThriftLandmark2D, y: ThriftLandmark2D): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator)

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[ThriftLandmark2D]) &&
      _passthroughFields == other.asInstanceOf[ThriftLandmark2D]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.name
    case 1 => this.pixels
    case 2 => this.uncertainty
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "ThriftLandmark2D"

  def _codec: ValidatingThriftStructCodec3[ThriftLandmark2D] = ThriftLandmark2D
}

