/**
 * Generated by Scrooge
 * version: 18.4.0
 * rev: b64bcb47af2451b2e51a1ed1b3876f6c06c642b3
 * built at: 20180410-144039
 */
package ch.unibas.cs.gravis.realsense

import scala.collection.Map
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder


object ThriftImage extends ValidatingThriftStructCodec3[ThriftImage] {
    val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
    val Struct = new TStruct("ThriftImage")
    val DataField = new TField("data", TType.STRING, 1)
    val DataFieldManifest = implicitly[Manifest[String]]
    val WidthField = new TField("width", TType.I32, 2)
    val WidthFieldManifest = implicitly[Manifest[Int]]
    val HeightField = new TField("height", TType.I32, 3)
    val HeightFieldManifest = implicitly[Manifest[Int]]

    /**
     * Field information in declaration order.
     */
    lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
            DataField,
            false,
            true,
            DataFieldManifest,
            _root_.scala.None,
            _root_.scala.None,
            immutable$Map.empty[String, String],
            immutable$Map.empty[String, String],
            None
        ),
        new ThriftStructFieldInfo(
            WidthField,
            false,
            true,
            WidthFieldManifest,
            _root_.scala.None,
            _root_.scala.None,
            immutable$Map.empty[String, String],
            immutable$Map.empty[String, String],
            None
        ),
        new ThriftStructFieldInfo(
            HeightField,
            false,
            true,
            HeightFieldManifest,
            _root_.scala.None,
            _root_.scala.None,
            immutable$Map.empty[String, String],
            immutable$Map.empty[String, String],
            None
        )
    )

    lazy val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]

    /**
     * Checks that all required fields are non-null.
     */
    def validate(_item: ThriftImage): Unit = {
        if (_item.data == null) throw new TProtocolException("Required field data cannot be null")
    }

    /**
     * Checks that the struct is a valid as a new instance. If there are any missing required or
     * construction required fields, return a non-empty list.
     */
    def validateNewInstance(item: ThriftImage): scala.Seq[com.twitter.scrooge.validation.Issue] = {
        val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

        if (item.data == null)
            buf += com.twitter.scrooge.validation.MissingRequiredField(fieldInfos.apply(0))
        buf ++= validateField(item.data)
        buf ++= validateField(item.width)
        buf ++= validateField(item.height)
        buf.toList
    }

    def withoutPassthroughFields(original: ThriftImage): ThriftImage =
        new Immutable(
            data = {
                val field = original.data
                field
            },
            width = {
                val field = original.width
                field
            },
            height = {
                val field = original.height
                field
            }
        )

    override def encode(_item: ThriftImage, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
    }


    private[this] def lazyDecode(_iprot: LazyTProtocol): ThriftImage = {

        var dataOffset: Int = -1
        var _got_data = false
        var width: Int = 0
        var _got_width = false
        var height: Int = 0
        var _got_height = false

        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
        val _start_offset = _iprot.offset

        _iprot.readStructBegin()
        while (!_done) {
            val _field = _iprot.readFieldBegin()
            if (_field.`type` == TType.STOP) {
                _done = true
            } else {
                _field.id match {
                    case 1 =>
                        _field.`type` match {
                            case TType.STRING =>
                                dataOffset = _iprot.offsetSkipString

                                _got_data = true
                            case _actualType =>
                                val _expectedType = TType.STRING
                                throw new TProtocolException(
                                    "Received wrong type for field 'data' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 2 =>
                        _field.`type` match {
                            case TType.I32 =>

                                width = readWidthValue(_iprot)
                                _got_width = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'width' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 3 =>
                        _field.`type` match {
                            case TType.I32 =>

                                height = readHeightValue(_iprot)
                                _got_height = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'height' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case _ =>
                        if (_passthroughFields == null)
                            _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                        _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
                }
                _iprot.readFieldEnd()
            }
        }
        _iprot.readStructEnd()

        if (!_got_data) throw new TProtocolException("Required field 'data' was not found in serialized data for struct ThriftImage")
        if (!_got_width) throw new TProtocolException("Required field 'width' was not found in serialized data for struct ThriftImage")
        if (!_got_height) throw new TProtocolException("Required field 'height' was not found in serialized data for struct ThriftImage")
        new LazyImmutable(
            _iprot,
            _iprot.buffer,
            _start_offset,
            _iprot.offset,
            dataOffset,
            width,
            height,
            if (_passthroughFields == null)
                NoPassthroughFields
            else
                _passthroughFields.result()
        )
    }

    override def decode(_iprot: TProtocol): ThriftImage =
        _iprot match {
            case i: LazyTProtocol => lazyDecode(i)
            case i => eagerDecode(i)
        }

    private[realsense] def eagerDecode(_iprot: TProtocol): ThriftImage = {
        var data: String = null
        var _got_data = false
        var width: Int = 0
        var _got_width = false
        var height: Int = 0
        var _got_height = false
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false

        _iprot.readStructBegin()
        while (!_done) {
            val _field = _iprot.readFieldBegin()
            if (_field.`type` == TType.STOP) {
                _done = true
            } else {
                _field.id match {
                    case 1 =>
                        _field.`type` match {
                            case TType.STRING =>
                                data = readDataValue(_iprot)
                                _got_data = true
                            case _actualType =>
                                val _expectedType = TType.STRING
                                throw new TProtocolException(
                                    "Received wrong type for field 'data' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 2 =>
                        _field.`type` match {
                            case TType.I32 =>
                                width = readWidthValue(_iprot)
                                _got_width = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'width' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case 3 =>
                        _field.`type` match {
                            case TType.I32 =>
                                height = readHeightValue(_iprot)
                                _got_height = true
                            case _actualType =>
                                val _expectedType = TType.I32
                                throw new TProtocolException(
                                    "Received wrong type for field 'height' (expected=%s, actual=%s).".format(
                                        ttypeToString(_expectedType),
                                        ttypeToString(_actualType)
                                    )
                                )
                        }
                    case _ =>
                        if (_passthroughFields == null)
                            _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
                        _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
                }
                _iprot.readFieldEnd()
            }
        }
        _iprot.readStructEnd()

        if (!_got_data) throw new TProtocolException("Required field 'data' was not found in serialized data for struct ThriftImage")
        if (!_got_width) throw new TProtocolException("Required field 'width' was not found in serialized data for struct ThriftImage")
        if (!_got_height) throw new TProtocolException("Required field 'height' was not found in serialized data for struct ThriftImage")
        new Immutable(
            data,
            width,
            height,
            if (_passthroughFields == null)
                NoPassthroughFields
            else
                _passthroughFields.result()
        )
    }

    def apply(
                 data: String,
                 width: Int,
                 height: Int
             ): ThriftImage =
        new Immutable(
            data,
            width,
            height
        )

    def unapply(_item: ThriftImage): _root_.scala.Option[_root_.scala.Tuple3[String, Int, Int]] = _root_.scala.Some(_item.toTuple)


    @inline private[realsense] def readDataValue(_iprot: TProtocol): String = {
        _iprot.readString()
    }

    @inline private def writeDataField(data_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(DataField)
        writeDataValue(data_item, _oprot)
        _oprot.writeFieldEnd()
    }

    @inline private def writeDataValue(data_item: String, _oprot: TProtocol): Unit = {
        _oprot.writeString(data_item)
    }

    @inline private[realsense] def readWidthValue(_iprot: TProtocol): Int = {
        _iprot.readI32()
    }

    @inline private def writeWidthField(width_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(WidthField)
        writeWidthValue(width_item, _oprot)
        _oprot.writeFieldEnd()
    }

    @inline private def writeWidthValue(width_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeI32(width_item)
    }

    @inline private[realsense] def readHeightValue(_iprot: TProtocol): Int = {
        _iprot.readI32()
    }

    @inline private def writeHeightField(height_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeFieldBegin(HeightField)
        writeHeightValue(height_item, _oprot)
        _oprot.writeFieldEnd()
    }

    @inline private def writeHeightValue(height_item: Int, _oprot: TProtocol): Unit = {
        _oprot.writeI32(height_item)
    }


    object Immutable extends ThriftStructCodec3[ThriftImage] {
        override def encode(_item: ThriftImage, _oproto: TProtocol): Unit = {
            _item.write(_oproto)
        }

        override def decode(_iprot: TProtocol): ThriftImage = ThriftImage.decode(_iprot)

        override lazy val metaData: ThriftStructMetaData[ThriftImage] = ThriftImage.metaData
    }

    /**
     * The default read-only implementation of ThriftImage.  You typically should not need to
     * directly reference this class; instead, use the ThriftImage.apply method to construct
     * new instances.
     */
    class Immutable(
                       val data: String,
                       val width: Int,
                       val height: Int,
                       override val _passthroughFields: immutable$Map[Short, TFieldBlob])
        extends ThriftImage {
        def this(
                    data: String,
                    width: Int,
                    height: Int
                ) = this(
            data,
            width,
            height,
            Map.empty[Short, TFieldBlob]
        )
    }

    /**
     * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
     * array byte on read.
     */
    private[this] class LazyImmutable(
                                         _proto: LazyTProtocol,
                                         _buf: Array[Byte],
                                         _start_offset: Int,
                                         _end_offset: Int,
                                         dataOffset: Int,
                                         val width: Int,
                                         val height: Int,
                                         override val _passthroughFields: immutable$Map[Short, TFieldBlob])
        extends ThriftImage {

        override def write(_oprot: TProtocol): Unit = {
            _oprot match {
                case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
                case _ => super.write(_oprot)
            }
        }

        lazy val data: String =
            if (dataOffset == -1)
                null
            else {
                _proto.decodeString(_buf, dataOffset)
            }

        /**
         * Override the super hash code to make it a lazy val rather than def.
         *
         * Calculating the hash code can be expensive, caching it where possible
         * can provide significant performance wins. (Key in a hash map for instance)
         * Usually not safe since the normal constructor will accept a mutable map or
         * set as an arg
         * Here however we control how the class is generated from serialized data.
         * With the class private and the contract that we throw away our mutable references
         * having the hash code lazy here is safe.
         */
        override lazy val hashCode = super.hashCode
    }

    /**
     * This Proxy trait allows you to extend the ThriftImage trait with additional state or
     * behavior and implement the read-only methods from ThriftImage using an underlying
     * instance.
     */
    trait Proxy extends ThriftImage {
        protected def _underlying_ThriftImage: ThriftImage

        override def data: String = _underlying_ThriftImage.data

        override def width: Int = _underlying_ThriftImage.width

        override def height: Int = _underlying_ThriftImage.height

        override def _passthroughFields = _underlying_ThriftImage._passthroughFields
    }

}

/**
 * Prefer the companion object's [[ch.unibas.cs.gravis.realsense.ThriftImage.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait ThriftImage
    extends ThriftStruct
        with _root_.scala.Product3[String, Int, Int]
        with ValidatingThriftStruct[ThriftImage]
        with java.io.Serializable {

    import ThriftImage._

    def data: String

    def width: Int

    def height: Int

    def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

    def _1 = data

    def _2 = width

    def _3 = height

    def toTuple: _root_.scala.Tuple3[String, Int, Int] = {
        (
            data,
            width,
            height
        )
    }


    /**
     * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
     * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
     * is known and not optional and set to None, then the field is serialized and returned.
     */
    def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
        lazy val _buff = new TMemoryBuffer(32)
        lazy val _oprot = new TCompactProtocol(_buff)
        _passthroughFields.get(_fieldId) match {
            case blob: _root_.scala.Some[TFieldBlob] => blob
            case _root_.scala.None => {
                val _fieldOpt: _root_.scala.Option[TField] =
                    _fieldId match {
                        case 1 =>
                            if (data ne null) {
                                writeDataValue(data, _oprot)
                                _root_.scala.Some(ThriftImage.DataField)
                            } else {
                                _root_.scala.None
                            }
                        case 2 =>
                            if (true) {
                                writeWidthValue(width, _oprot)
                                _root_.scala.Some(ThriftImage.WidthField)
                            } else {
                                _root_.scala.None
                            }
                        case 3 =>
                            if (true) {
                                writeHeightValue(height, _oprot)
                                _root_.scala.Some(ThriftImage.HeightField)
                            } else {
                                _root_.scala.None
                            }
                        case _ => _root_.scala.None
                    }
                _fieldOpt match {
                    case _root_.scala.Some(_field) =>
                        _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
                    case _root_.scala.None =>
                        _root_.scala.None
                }
            }
        }
    }

    /**
     * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
     */
    def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
        (ids flatMap { id => getFieldBlob(id) map {
            id -> _
        }
        }).toMap

    /**
     * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
     * field, the blob is decoded and the field is set to the decoded value.  If the field
     * is unknown and passthrough fields are enabled, then the blob will be stored in
     * _passthroughFields.
     */
    def setField(_blob: TFieldBlob): ThriftImage = {
        var data: String = this.data
        var width: Int = this.width
        var height: Int = this.height
        var _passthroughFields = this._passthroughFields
        _blob.id match {
            case 1 =>
                data = readDataValue(_blob.read)
            case 2 =>
                width = readWidthValue(_blob.read)
            case 3 =>
                height = readHeightValue(_blob.read)
            case _ => _passthroughFields += (_blob.id -> _blob)
        }
        new Immutable(
            data,
            width,
            height,
            _passthroughFields
        )
    }

    /**
     * If the specified field is optional, it is set to None.  Otherwise, if the field is
     * known, it is reverted to its default value; if the field is unknown, it is removed
     * from the passthroughFields map, if present.
     */
    def unsetField(_fieldId: Short): ThriftImage = {
        var data: String = this.data
        var width: Int = this.width
        var height: Int = this.height

        _fieldId match {
            case 1 =>
                data = null
            case 2 =>
                width = 0
            case 3 =>
                height = 0
            case _ =>
        }
        new Immutable(
            data,
            width,
            height,
            _passthroughFields - _fieldId
        )
    }

    /**
     * If the specified field is optional, it is set to None.  Otherwise, if the field is
     * known, it is reverted to its default value; if the field is unknown, it is removed
     * from the passthroughFields map, if present.
     */
    def unsetData: ThriftImage = unsetField(1)

    def unsetWidth: ThriftImage = unsetField(2)

    def unsetHeight: ThriftImage = unsetField(3)


    override def write(_oprot: TProtocol): Unit = {
        ThriftImage.validate(this)
        _oprot.writeStructBegin(Struct)
        if (data ne null) writeDataField(data, _oprot)
        writeWidthField(width, _oprot)
        writeHeightField(height, _oprot)
        if (_passthroughFields.nonEmpty) {
            _passthroughFields.values.foreach {
                _.write(_oprot)
            }
        }
        _oprot.writeFieldStop()
        _oprot.writeStructEnd()
    }

    def copy(
                data: String = this.data,
                width: Int = this.width,
                height: Int = this.height,
                _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
            ): ThriftImage =
        new Immutable(
            data,
            width,
            height,
            _passthroughFields
        )

    override def canEqual(other: Any): Boolean = other.isInstanceOf[ThriftImage]

    private def _equals(x: ThriftImage, y: ThriftImage): Boolean =
        x.productArity == y.productArity &&
            x.productIterator.sameElements(y.productIterator)

    override def equals(other: Any): Boolean =
        canEqual(other) &&
            _equals(this, other.asInstanceOf[ThriftImage]) &&
            _passthroughFields == other.asInstanceOf[ThriftImage]._passthroughFields

    override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

    override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


    override def productArity: Int = 3

    override def productElement(n: Int): Any = n match {
        case 0 => this.data
        case 1 => this.width
        case 2 => this.height
        case _ => throw new IndexOutOfBoundsException(n.toString)
    }

    override def productPrefix: String = "ThriftImage"

    def _codec: ValidatingThriftStructCodec3[ThriftImage] = ThriftImage
}

